app:
  id: acanTest1
apollo:
  meta: http://localhost:8080
  bootstrap:
    enabled: true
    namespaces: dev.yml,TEST1.namespase1.properties

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:mysql://localhost:3306
    username: root
    password: 123456

server:
  port: 8086

mxn:
  name: acanonnn
